// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanckEnergyMVC.DAL;

#nullable disable

namespace PlanckEnergyMVC.Migrations
{
    [DbContext(typeof(MaterialDbContext))]
    partial class MaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanckEnergyMVC.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_angle_alpha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_angle_beta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_angle_gamma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_length_a")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_length_b")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_length_c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_cell_volume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_chemical_formula_moiety")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_space_group_name_Hall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_symmetry_Int_Tables_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_symmetry_cell_setting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_symmetry_space_group_name_H_M")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
